//
// The contents of this file are subject to the Mozilla Public
// License Version 1.1 (the "License"); you may not use this file
// except in compliance with the License. You may obtain a copy
// of the License at http://www.mozilla.org/MPL/
//
// Software distributed under the License is distributed on an
// "AS IS" basis, WITHOUT WARRANTY OF ANY KIND, either express or
// implied. See the License for the specific language governing
// rights and limitations under the License.
//
// The Original Code is State Machine Compiler (SMC).
//
// The Initial Developer of the Original Code is Charles W. Rapp.
// Portions created by Charles W. Rapp are
// Copyright (C) 2005 - 2009, 2019. Charles W. Rapp.
// All Rights Reserved.
//
// Port to Python by Francois Perrad, francois.perrad@gadz.org
// Copyright 2004-2009, Francois Perrad.
// All Rights Reserved.
//
// Contributor(s):
//   Eitan Suez contributed examples/Ant.
//   (Name withheld) contributed the C# code generation and
//   examples/C#.
//   Francois Perrad contributed the Python code generation and
//   examples/Python.
//   Chris Liscio contributed the Objective-C code generation
//   and examples/ObjC.
//
// RCS ID
// $Id: SmcPythonGenerator.java,v 1.17 2014/07/12 08:18:18 fperrad Exp $
//
// CHANGE LOG
// (See the bottom of this file.)
//

package net.sf.smc.generator;

import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import net.sf.smc.model.SmcAction;
import net.sf.smc.model.SmcElement;
import net.sf.smc.model.SmcElement.TransType;
import net.sf.smc.model.SmcFSM;
import net.sf.smc.model.SmcGuard;
import net.sf.smc.model.SmcMap;
import net.sf.smc.model.SmcParameter;
import net.sf.smc.model.SmcState;
import net.sf.smc.model.SmcTransition;
import net.sf.smc.model.SmcVisitor;
import net.sf.smc.model.TargetLanguage;

/**
 * Visits the abstract syntax tree, emitting Python code.
 * @see SmcElement
 * @see SmcCodeGenerator
 * @see SmcVisitor
 * @see SmcOptions
 *
 * @author Francois Perrad
 */

public final class SmcPythonGenerator
    extends SmcCodeGenerator
{
//---------------------------------------------------------------
// Member data
//

//---------------------------------------------------------------
// Member methods
//

    //-----------------------------------------------------------
    // Constructors.
    //

    /**
     * Creates a Python code generator for the given options.
     * @param options The target code generator options.
     */
    public SmcPythonGenerator(final SmcOptions options)
    {
        super (options, TargetLanguage.PYTHON.suffix());
    } // end of SmcPythonGenerator(SmcOptions)

    //
    // end of Constructors.
    //-----------------------------------------------------------

    //-----------------------------------------------------------
    // SmcVisitor Abstract Method Impelementation.
    //

    /**
     * Emits Python code for the finite state machine.
     * @param fsm emit Python code for this finite state machine.
     */
    @Override
    public void visit(final SmcFSM fsm)
    {
        String context = fsm.getContext();
        String rawSource = fsm.getSource();
        String startState = fsm.getStartState();
        String pythonState;
        List<SmcMap> maps = fsm.getMaps();
        List<SmcTransition> transitions;
        List<SmcParameter> params;
        int index;

        mTarget.println("# ex: set ro:");
        mTarget.println("# DO NOT EDIT.");
        mTarget.println(
            "# generated by smc (http://smc.sourceforge.net/)");
        mTarget.print("# from file : ");
        mTarget.print(mSrcfileBase);
        mTarget.println(".sm");
        mTarget.println();

        // Dump out the raw target code, if any.
        if (rawSource != null && rawSource.length () > 0)
        {
            mTarget.println(rawSource);
            mTarget.println();
        }

        mTarget.println("import statemap");
        mTarget.println();

        // Do user-specified imports now.
        for (String imp: fsm.getImports())
        {
            mTarget.print("import ");
            mTarget.println(imp);
        }

        // Declare the inner state class.
        mTarget.println();
        mTarget.print("class ");
        mTarget.print(context);
        mTarget.println("State(statemap.State):");

        mTarget.println();
        mTarget.println("    def Entry(self, fsm):");
        mTarget.println("        pass");
        mTarget.println();
        mTarget.println("    def Exit(self, fsm):");
        mTarget.println("        pass");
        mTarget.println();

        // Get the transition list.
        // Generate the default transition definitions.
        transitions = fsm.getTransitions();
        for (SmcTransition trans: transitions)
        {
            params = trans.getParameters();

            // Don't generate the Default transition here.
            if (trans.getName().equals("Default") == false)
            {
                mTarget.print("    def ");
                mTarget.print(trans.getName());
                mTarget.print("(self, fsm");

                for (SmcParameter param: params)
                {
                    mTarget.print(", ");
                    param.accept(this);
                }

                mTarget.println("):");

                // If this method is reached, that means that
                // this transition was passed to a state which
                // does not define the transition. Call the
                // state's default transition method.
                mTarget.println("        self.Default(fsm)");
                mTarget.println();
            }
        }

        // Generate the overall Default transition for all maps.
        mTarget.println("    def Default(self, fsm):");

        if (mDebugLevel >= DEBUG_LEVEL_0)
        {
            mTarget.println(
                "        if fsm.getDebugFlag() == True:");
            mTarget.println(
                "            fsm.getDebugStream().write('TRANSITION   : Default\\n')");
        }

        mTarget.println(
            "        msg = \"\\n\\tState: %s\\n\\tTransition: %s\" % (");
        mTarget.println(
            "            fsm.getState().getName(), fsm.getTransition())");
        mTarget.println(
            "        raise statemap.TransitionUndefinedException(msg)");

        // Generate the getTransitions() method.
        if (mReflectFlag)
        {
            mTarget.println();
            mTarget.println("    def getTransitions (self):");
            mTarget.println("        return self._transitions");
        }

        // Have each map print out its target code now.
        for (SmcMap map: maps)
        {
            map.accept(this);
        }

        // The state name "map::state" must be changed to
        // "map.state".
        if ((index = startState.indexOf("::")) >= 0)
        {
            pythonState =
                startState.substring(0, index) +
                "." +
                startState.substring(index + 2);
        }
        else
        {
            pythonState = startState;
        }

        // The context class contains all the state classes as
        // inner classes, so generate the context first rather
        // than last.
        mTarget.println();
        mTarget.print("class ");
        mTarget.print(context);
        mTarget.println("_sm(statemap.FSMContext):");
        mTarget.println();

        // Generate the context class' constructor.
        mTarget.println("    def __init__(self, owner):");
        mTarget.print(
            "        statemap.FSMContext.__init__(self, ");
        mTarget.print(pythonState);
        mTarget.println(")");
        mTarget.println("        self._owner = owner");
        mTarget.println();

        // Don't generate the transition methods.
        // Use automatic delegation.
        mTarget.println("    def __getattr__(self, attrib):");
        mTarget.println("        def trans_sm(*arglist):");
        mTarget.println("            self._transition = attrib");
        mTarget.println("            getattr(self.getState(), attrib)(self, *arglist)");
        mTarget.println("            self._transition = None");
        mTarget.println("        return trans_sm");
        mTarget.println();

        // enterStartState()
        // Execute the start state's entry actions.
        mTarget.println("    def enterStartState(self):");
        mTarget.println("        self._state.Entry(self)");
        mTarget.println();

        // getOwner() method.
        mTarget.println("    def getOwner(self):");
        mTarget.println("        return self._owner");
        mTarget.println();

        if (mReflectFlag)
        {
            // getStates() method.
            mTarget.println("    _States = (");
            for (SmcMap map: maps)
            {
                String mapName = map.getName();

                for (SmcState state: map.getStates())
                {
                    mTarget.print("        ");
                    mTarget.print(mapName);
                    mTarget.print(".");
                    mTarget.print(state.getClassName());
                    mTarget.println(",");
                }
            }
            mTarget.println("    )");
            mTarget.println("    def getStates(self):");
            mTarget.println("        return self._States");
            mTarget.println();

            // getTransitions() method.
            mTarget.println("    _transitions = (");
            for (SmcTransition trans: transitions)
            {
                mTarget.print("        '");
                mTarget.print(trans.getName());
                mTarget.println("',");
            }
            mTarget.println("    )");
            mTarget.println("    def getTransitions(self):");
            mTarget.println("        return self._transitions");
            mTarget.println();
        }

        mTarget.println("# Local variables:");
        mTarget.println("#  buffer-read-only: t");
        mTarget.println("# End:");

        return;
    } // end of visit(SmcFSM)

    /**
     * Emits Python code for the FSM map.
     * @param map emit Python code for this map.
     */
    @Override
    public void visit(final SmcMap map)
    {
        List<SmcTransition> definedDefaultTransitions;
        SmcState defaultState = map.getDefaultState();
        String context = map.getFSM().getContext();
        String mapName = map.getName();
        List<SmcState> states = map.getStates();
        boolean needPass = true;

        // Initialize the default transition list to all the
        // default state's transitions.
        if (defaultState != null)
        {
            definedDefaultTransitions =
                    defaultState.getTransitions();
        }
        else
        {
            definedDefaultTransitions = new ArrayList<>();
        }

        // Declare the map default state class.
        mTarget.println();
        mTarget.print("class ");
        mTarget.print(mapName);
        mTarget.print("_Default(");
        mTarget.print(context);
        mTarget.println("State):");

        // Declare the user-defined default transitions first.
        for (SmcTransition transition: definedDefaultTransitions)
        {
            needPass = false;
            transition.accept(this);
        }

        if (needPass && mReflectFlag == false)
        {
            mTarget.println("    pass");
        }

        // If -reflect was specified, then generate the
        // _transitions map.
        if (mReflectFlag)
        {
            List<SmcTransition> allTransitions =
                map.getFSM().getTransitions();
            String transName;
            int transDefinition;

            // Now output the transition collection's
            // initialization.
            mTarget.println();
            mTarget.println("    _transitions = dict(");

            // Now place all transition names and states into the
            // map.
            for (SmcTransition transition: allTransitions)
            {
                transName = transition.getName();

                // If the transition is defined in this map's
                // default state, then the value is 2.
                if (definedDefaultTransitions.contains(transition))
                {
                    transDefinition = 2;
                }
                // Otherwise the value is 0 - undefined.
                else
                {
                    transDefinition = 0;
                }

                mTarget.print("        ");
                mTarget.print(transName);
                mTarget.print(" = ");
                mTarget.print(transDefinition);
                mTarget.println(",");
            }
            mTarget.println("    )");
        }

        // Have each state now generate its code. Each state
        // class is an inner class.
        for (SmcState state: states)
        {
            state.accept(this);
        }

        // Declare and initialize the map class.
        mTarget.println();
        mTarget.print("class ");
        mTarget.print(mapName);
        mTarget.println("(object):");
        mTarget.println();

        for (SmcState state: states)
        {
            mTarget.print("    ");
            mTarget.print(state.getInstanceName());
            mTarget.print(" = ");
            mTarget.print(mapName);
            mTarget.print('_');
            mTarget.print(state.getClassName());
            mTarget.print("('");
            mTarget.print(mapName);
            mTarget.print('.');
            mTarget.print(state.getClassName());
            mTarget.print("', ");
            mTarget.print(SmcMap.getNextStateId());
            mTarget.println(")");
        }

        // Instantiate a default state as well.
        mTarget.print("    Default = ");
        mTarget.print(mapName);
        mTarget.print("_Default('");
        mTarget.print(mapName);
        mTarget.println(".Default', -1)");

        return;
    } // end of visit(SmcMap)

    /**
     * Emits Python code for this FSM state.
     * @param state emits Python code for this state.
     */
    @Override
    public void visit(final SmcState state)
    {
        SmcMap map = state.getMap();
        String mapName = map.getName();
        String stateName = state.getClassName();
        List<SmcAction> actions;
        String indent2;
        boolean needPass = true;

        // Declare the inner state class.
        mTarget.println();
        mTarget.print("class ");
        mTarget.print(mapName);
        mTarget.print('_');
        mTarget.print(stateName);
        mTarget.print("(");
        mTarget.print(mapName);
        mTarget.println("_Default):");

        // Add the Entry() and Exit() member functions if this
        // state defines them.
        actions = state.getEntryActions();
        if (actions != null && actions.size() > 0)
        {
            needPass = false;

            mTarget.println();
            mTarget.println("    def Entry(self, fsm):");

            // Declare the "ctxt" local variable.
            mTarget.println("        ctxt = fsm.getOwner()");

            // Generate the actions associated with this code.
            indent2 = mIndent;
            mIndent = "        ";
            for (SmcAction action: actions)
            {
                action.accept(this);
            }
            mIndent = indent2;
        }

        actions = state.getExitActions();
        if (actions != null && actions.size() > 0)
        {
            needPass = false;

            mTarget.println();
            mTarget.println("    def Exit(self, fsm):");

            // Declare the "ctxt" local variable.
            mTarget.println("        ctxt = fsm.getOwner()");

            // Generate the actions associated with this code.
            indent2 = mIndent;
            mIndent = "        ";
            for (SmcAction action: actions)
            {
                action.accept(this);
            }
            mIndent = indent2;
        }

        // Have each transition generate its code.
        for (SmcTransition transition: state.getTransitions())
        {
            needPass = false;

            transition.accept(this);
        }

        if (needPass && mReflectFlag == false)
        {
            mTarget.println("    pass");
        }

        // If -reflect was specified, then generate the
        // _transitions table.
        if (mReflectFlag)
        {
            List<SmcTransition> allTransitions =
                map.getFSM().getTransitions();
            List<SmcTransition> stateTransitions =
                state.getTransitions();
            SmcState defaultState = map.getDefaultState();
            List<SmcTransition> defaultTransitions;
            String transName;
            int transDefinition;

            // Initialize the default transition list to all the
            // default state's transitions.
            if (defaultState != null)
            {
                defaultTransitions =
                    defaultState.getTransitions();
            }
            else
            {
                defaultTransitions = new ArrayList<>();
            }

            // Now output the transition collection's
            // initialization.
            mTarget.println();
            mTarget.println("    _transitions = dict(");

            // Now place all transition names and states into the
            // map.
            for (SmcTransition transition: allTransitions)
            {
                transName = transition.getName();

                // If the transition is in this state, then its
                // value is 1.
                if (stateTransitions.contains(transition))
                {
                    transDefinition = 1;
                }
                // If the transition is defined in this map's
                // default state, then the value is 2.
                else if (defaultTransitions.contains(transition))
                {
                    transDefinition = 2;
                }
                // Otherwise the value is 0 - undefined.
                else
                {
                    transDefinition = 0;
                }

                mTarget.print("        ");
                mTarget.print(transName);
                mTarget.print(" = ");
                mTarget.print(transDefinition);
                mTarget.println(",");
            }
            mTarget.println("    )");
        }

        return;
    } // end of visit(SmcState)

    /**
     * Emits Python code for this FSM state transition.
     * @param transition emits Python code for this state transition.
     */
    @Override
    public void visit(final SmcTransition transition)
    {
        SmcState state = transition.getState();
        SmcMap map = state.getMap();
        String context = map.getFSM().getContext();
        String mapName = map.getName();
        String stateName = state.getClassName();
        String instanceName = state.getInstanceName();
        String transName = transition.getName();
        List<SmcParameter> parameters =
            transition.getParameters();
        List<SmcGuard> guards = transition.getGuards();
        Iterator<SmcGuard> git = guards.iterator();
        SmcGuard guard;
        SmcGuard nullGuard = null;

        mTarget.println();
        mTarget.print("    def ");
        mTarget.print(transName);
        mTarget.print("(self, fsm");

        // Add user-defined parameters.
        for (SmcParameter param: parameters)
        {
            mTarget.print(", ");
            param.accept(this);
        }
        mTarget.println("):");

        // All transitions have a "ctxt" local variable.
        // 8/14/2003:
        // Do this only if there are any transition actions or
        // guard conditions which reference it.
        if (transition.hasCtxtReference())
        {
            mTarget.println("        ctxt = fsm.getOwner()");
        }

        // Output transition to debug stream.
        if (mDebugLevel >= DEBUG_LEVEL_0)
        {
            mTarget.println(
                "        if fsm.getDebugFlag() == True:");
            mTarget.print(
                "            fsm.getDebugStream().write(\"");
            mTarget.print("LEAVING STATE   : ");
            mTarget.print(mapName);
            mTarget.print(".");
            mTarget.print(stateName);
            mTarget.println("\\n\")");
            mTarget.println();
        }

        // Loop through the guards and print each one.
        mIndent = "        ";
        mGuardIndex = 0;
        mGuardCount = guards.size();
        while (git.hasNext())
        {
            guard = git.next();

            // Count up the guards with no condition.
            if (guard.getCondition().isEmpty())
            {
                nullGuard = guard;
            }
            else
            {
                guard.accept(this);
                ++mGuardIndex;
            }
        }

        // Is there an explicitly defined unguarded transition?
        if (nullGuard != null)
        {
            // Does this guard have any actions or is this guard
            // *not* an internal loopback transition?
            if (nullGuard.hasActions() ||
                !(nullGuard.getEndState()).equals(SmcElement.NIL_STATE) ||
                nullGuard.getTransType() == TransType.TRANS_PUSH ||
                nullGuard.getTransType() == TransType.TRANS_POP)
            {
                // Need to output either the action and/or the
                // next state, so output the guard.
                nullGuard.accept(this);
            }

            mTarget.println();
        }
        // If all guards have a condition, then create a final
        // "else" clause which passes control to the default
        // transition. Pass all arguments into the default
        // transition.
        else if (mGuardIndex > 0)
        {
            mTarget.println("        else:");

            // Call the super class' transition method using
            // the class name.
            mTarget.print("            ");
            if (instanceName.equals("DefaultState") == false)
            {
                mTarget.print(mapName);
                mTarget.print("_Default.");
            }
            else
            {
                mTarget.print(context);
                mTarget.print("State.");
            }
            mTarget.print(transName);
            mTarget.print("(self, fsm");

            for (SmcParameter param: parameters)
            {
                mTarget.print(", ");
                param.accept(this);
            }

            mTarget.println(")");
            mTarget.print("        ");
        }
        // Need to add a final newline after a multiguard block.
        else if (mGuardCount > 1)
        {
            mTarget.println();
        }

        return;
    } // end of visit(SmcTransition)

    /**
     * Emits Python code for this FSM transition guard.
     * @param guard emits Python code for this transition guard.
     */
    @Override
    public void visit(final SmcGuard guard)
    {
        SmcTransition transition = guard.getTransition();
        SmcState state = transition.getState();
        SmcMap map = state.getMap();
        String mapName = map.getName();
        String stateName = state.getClassName();
        String transName = transition.getName();
        TransType transType = guard.getTransType();
        boolean loopbackFlag;
        String indent2;
        String indent3;
        String indent4;
        String endStateName = guard.getEndState();
        String fqEndStateName = "";
        String pushStateName = guard.getPushState();
        String condition = guard.getCondition();
        List<SmcAction> actions = guard.getActions();

        // If this guard's end state is not of the form
        // "map::state", then prepend the map name to the
        // state name.
        // DON'T DO THIS IF THIS IS A POP TRANSITION!
        // The "state" is actually a transition name.
        if (transType != TransType.TRANS_POP &&
            endStateName.length () > 0 &&
            endStateName.equals(SmcElement.NIL_STATE) == false)
        {
            endStateName = scopeStateName(endStateName, mapName);
        }

        // Qualify the state and push state names as well.
        stateName = scopeStateName(stateName, mapName);
        pushStateName = scopeStateName(pushStateName, mapName);

        loopbackFlag = isLoopback(transType, endStateName);

        // The guard code generation is a bit tricky. The first
        // question is how many guards are there? If there are
        // more than one, then we will need to generate the
        // proper "if-then-else" code.
        if (mGuardCount > 1)
        {
            indent2 = mIndent + "    ";

            // There are multiple guards. Is this the first
            // guard?
            if (mGuardIndex == 0 && condition.length() > 0)
            {
                // Yes, this is the first. This means an "if"
                // should be used.
                mTarget.print(mIndent);
                mTarget.print("if ");
                mTarget.print(condition);
                mTarget.println(" :");
            }
            else if (condition.length() > 0)
            {
                // No, this is not the first transition but it
                // does have a condition. Use an "else if".
                mTarget.print(mIndent);
                mTarget.print("elif ");
                mTarget.print(condition);
                mTarget.println(" :");
            }
            else
            {
                // This is not the first transition and it has
                // no condition.
                mTarget.print(mIndent);
                mTarget.println("else:");
            }
        }
        // There is only one guard. Does this guard have
        // a condition?
        else if (condition.length() == 0)
        {
            // No. This is a plain, old. vanilla transition.
            indent2 = mIndent;
        }
        else
        {
            // Yes there is a condition.
            indent2 = mIndent + "    ";

            mTarget.print(mIndent);
            mTarget.print("if ");
            mTarget.print(condition);
            mTarget.println(" :");
        }

        // Now that the necessary conditions are in place, it's
        // time to dump out the transition's actions. First, do
        // the proper handling of the state change. If this
        // transition has no actions, then set the end state
        // immediately. Otherwise, unset the current state so
        // that if an action tries to issue a transition, it will
        // fail.
        if (actions.isEmpty() && !endStateName.isEmpty())
        {
            fqEndStateName = endStateName;
        }
        else if (!actions.isEmpty())
        {
            // Save away the current state if this is a loopback
            // transition. Storing current state allows the
            // current state to be cleared before any actions are
            // executed. Remember: actions are not allowed to
            // issue transitions and clearing the current state
            // prevents them from doing do.
            if (loopbackFlag)
            {
                fqEndStateName = "endState";

                mTarget.print(indent2);
                mTarget.print(fqEndStateName);
                mTarget.println(" = fsm.getState()");
            }
            else
            {
                fqEndStateName = endStateName;
            }
        }

        // Dump out the exit actions - but only for the first
        // guard.
        // v. 1.0, beta 3: Not any more. The exit actions are
        // executed only if 1) this is a standard, non-loopback
        // transition or a pop transition.
        if (transType == TransType.TRANS_POP ||
            loopbackFlag == false)
        {
            if (mDebugLevel >= DEBUG_LEVEL_1)
            {
                mTarget.print(indent2);
                mTarget.println(
                    "if fsm.getDebugFlag() == True:");
                mTarget.print(indent2);
                mTarget.print("    fsm.getDebugStream().write(");
                mTarget.print("\"BEFORE EXIT     : ");
                mTarget.print(stateName);
                mTarget.println(".Exit(fsm)\\n\")");
                mTarget.println();
            }

            mTarget.print(indent2);
            mTarget.println("fsm.getState().Exit(fsm)");

            if (mDebugLevel >= DEBUG_LEVEL_1)
            {
                mTarget.print(indent2);
                mTarget.println(
                    "if fsm.getDebugFlag() == True:");
                mTarget.print(indent2);
                mTarget.print("    fsm.getDebugStream().write(");
                mTarget.print("\"AFTER EXIT      : ");
                mTarget.print(stateName);
                mTarget.println(".Exit(fsm)\\n\")");
                mTarget.println();
            }
        }

        if (mDebugLevel >= DEBUG_LEVEL_0)
        {
            List<SmcParameter> parameters =
                transition.getParameters();
            Iterator<SmcParameter> pit;
            String sep;

            mTarget.print(indent2);
            mTarget.println(
                "if fsm.getDebugFlag() == True:");
            mTarget.print(indent2);
            mTarget.print(
                "    fsm.getDebugStream().write(\"");
            mTarget.print("ENTER TRANSITION: ");
            mTarget.print(stateName);
            mTarget.print(".");
            mTarget.print(transName);
            mTarget.print("(");
            for (pit = parameters.iterator(), sep = "";
                 pit.hasNext();
                 sep = ", ")
            {
                mTarget.print(sep);
                (pit.next()).accept(this);
            }
            mTarget.println(")\\n\")");
            mTarget.println();
        }

        // Dump out this transition's actions.
        if (actions.isEmpty())
        {
            // If this is an if or else body, then give it a
            // pass.
            if (!condition.isEmpty() || mGuardCount > 1)
            {
                mTarget.print(indent2);
                mTarget.println("# No actions.");
                mTarget.print(indent2);
                mTarget.println("pass");
            }
            // If there are:
            // 3. Only one guard,
            // 4. No condition,
            // 5. No actions,
            // 6. Not a loopback, push or pop transition and
            // 7. No debug code being generated.
            // then give this transition a pass.
            else if (mGuardCount == 1 &&
                     transType != TransType.TRANS_PUSH &&
                     transType != TransType.TRANS_POP &&
                     loopbackFlag &&
                     mDebugLevel == NO_DEBUG_OUTPUT)
            {
                mTarget.print(indent2);
                mTarget.println("# No actions.");
                mTarget.print(indent2);
                mTarget.println("pass");
            }

            indent3 = indent2;
        }
        else
        {
            // Now that we are in the transition, clear the
            // current state.
            mTarget.print(indent2);
            mTarget.println("fsm.clearState()");

            // v. 2.0.0: Place the actions inside a try/finally
            // block. This way the state will be set before an
            // exception leaves the transition method.
            // v. 2.2.0: Check if the user has turned off this
            // feature first.
            if (mNoCatchFlag == false)
            {
                mTarget.print(indent2);
                mTarget.println("try:");

                indent3 = indent2 + "    ";
            }
            else
            {
                indent3 = indent2;
            }

            indent4 = mIndent;
            mIndent = indent3;

            for (SmcAction action: actions)
            {
                action.accept(this);
            }

            mIndent = indent4;

            // v. 2.2.0: Check if the user has turned off this
            // feature first.
            if (mNoCatchFlag == false)
            {
                mTarget.print(indent2);
                mTarget.println("finally:");
            }
        }

        if (mDebugLevel >= DEBUG_LEVEL_0)
        {
            List<SmcParameter> parameters =
                transition.getParameters();
            Iterator<SmcParameter> pit;
            String sep;

            mTarget.print(indent3);
            mTarget.println(
                "if fsm.getDebugFlag() == True:");
            mTarget.print(indent3);
            mTarget.print(
                "    fsm.getDebugStream().write(\"");
            mTarget.print("EXIT TRANSITION : ");
            mTarget.print(stateName);
            mTarget.print(".");
            mTarget.print(transName);
            mTarget.print("(");
            for (pit = parameters.iterator(), sep = "";
                 pit.hasNext();
                 sep = ", ")
            {
                mTarget.print(sep);
                (pit.next()).accept(this);
            }
            mTarget.println(")\\n\")");
            mTarget.println();
        }

        // Print the setState() call, if necessary. Do NOT
        // generate the set state it:
        // 1. The transition has no actions AND is a loopback OR
        // 2. This is a push or pop transition.
        if (transType == TransType.TRANS_SET &&
            (actions.isEmpty() == false ||
             loopbackFlag == false))
        {
            mTarget.print(indent3);
            mTarget.print("fsm.setState(");
            mTarget.print(fqEndStateName);
            mTarget.println(")");
        }
        else if (transType == TransType.TRANS_PUSH)
        {
            // Set the next state so this it can be pushed
            // onto the state stack. But only do so if a clear
            // state was done.
            if (loopbackFlag == false ||
                actions.isEmpty() == false)
            {
                mTarget.print(indent3);
                mTarget.print("fsm.setState(");
                mTarget.print(fqEndStateName);
                mTarget.println(")");
            }

            // Before doing the push, execute the end state's
            // entry actions (if any) if this is not a loopback.
            if (loopbackFlag == false)
            {
                if (mDebugLevel >= DEBUG_LEVEL_1)
                {
                    mTarget.print(indent3);
                    mTarget.println(
                        "if fsm.getDebugFlag() == True:");
                    mTarget.print(indent3);
                    mTarget.print(
                        "    fsm.getDebugStream().write(\"");
                    mTarget.print("BEFORE ENTRY    : ");
                    mTarget.print(fqEndStateName);
                    mTarget.println(".Entry(fsm)\\n\")");
                    mTarget.println();
                }

                mTarget.print(indent3);
                mTarget.println("fsm.getState().Entry(fsm)");

                if (mDebugLevel >= DEBUG_LEVEL_1)
                {
                    mTarget.print(indent3);
                    mTarget.println(
                        "if fsm.getDebugFlag() == True:");
                    mTarget.print(indent3);
                    mTarget.print(
                        "    fsm.getDebugStream().write(");
                    mTarget.print("\"AFTER ENTRY     : ");
                    mTarget.print(fqEndStateName);
                    mTarget.println(".Entry(fsm)\\n\")");
                    mTarget.println();
                }
            }

            mTarget.print(indent3);
            mTarget.print("fsm.pushState(");
            mTarget.print(pushStateName);
            mTarget.println(")");
        }
        else if (transType == TransType.TRANS_POP)
        {
            mTarget.print(indent3);
            mTarget.println("fsm.popState()");
        }

        // Perform the new state's enty actions.
        // v. 1.0, beta 3: Not any more. The entry actions are
        // executed only if 1) this is a standard, non-loopback
        // transition or a push transition.
        if ((transType == TransType.TRANS_SET &&
             loopbackFlag == false) ||
             transType == TransType.TRANS_PUSH)
        {
            if (mDebugLevel >= DEBUG_LEVEL_1)
            {
                mTarget.print(indent3);
                mTarget.println(
                    "if fsm.getDebugFlag() == True:");
                mTarget.print(indent3);
                mTarget.print("    fsm.getDebugStream().write(");
                mTarget.print("\"BEFORE ENTRY    : ");
                mTarget.print(fqEndStateName);
                mTarget.println(".Entry(fsm)\\n\")");
                mTarget.println();
            }

            mTarget.print(indent3);
            mTarget.println("fsm.getState().Entry(fsm)");

            if (mDebugLevel >= DEBUG_LEVEL_1)
            {
                mTarget.print(indent3);
                mTarget.println(
                    "if fsm.getDebugFlag() == True:");
                mTarget.print(indent3);
                mTarget.print("    fsm.getDebugStream().write(");
                mTarget.print("\"AFTER ENTRY     : ");
                mTarget.print(fqEndStateName);
                mTarget.println(".Entry(fsm)\\n\")");
                mTarget.println();
            }
        }

        // If there is a transition associated with the pop, then
        // issue that transition here.
        if (transType == TransType.TRANS_POP &&
            endStateName.equals(SmcElement.NIL_STATE) == false &&
            endStateName.length() > 0)
        {
            String popArgs = guard.getPopArgs();

            mTarget.print(indent2);
            mTarget.print("fsm.");
            mTarget.print(endStateName);
            mTarget.print("(");

            // Output any and all pop arguments.
            if (popArgs.length() > 0)
            {
                mTarget.print(popArgs);
                mTarget.println();
                mTarget.print(indent2);
                mTarget.println(")");
            }
            else
            {
                mTarget.println(")");
            }
        }

        return;
    } // end of visit(SmcGuard)

    /**
     * Emits Python code for this FSM action.
     * @param action emits Python code for this action.
     */
    @Override
    public void visit(final SmcAction action)
    {
        String name = action.getName();
        List<String> arguments = action.getArguments();

        if (action.isProperty())
        {
            mTarget.print(mIndent);
            mTarget.print("ctxt.");
            mTarget.print(name);
            mTarget.print(" = ");
            mTarget.println(arguments.get(0));
        }
        else
        {
            // Need to distinguish between FSMContext actions and
            // application class actions. If the action is
            // "emptyStateStack", then pass it to the context.
            // Otherwise, let the application class handle it.
            mTarget.print(mIndent);
            if (action.isEmptyStateStack())
            {
                mTarget.println("fsm.emptyStateStack()");
            }
            else
            {
                Iterator<String> it;
                String sep;

                mTarget.print("ctxt.");
	        mTarget.print(name);
	        mTarget.print("(");

	        for (it = arguments.iterator(), sep = "";
	             it.hasNext();
	             sep = ", ")
	        {
	            mTarget.print(sep);
	            mTarget.print(it.next());
	        }

	        mTarget.println(")");
	    }
        }

        return;
    } // end of visit(SmcAction)

    /**
     * Emits Python code for this transition parameter.
     * @param parameter emits Python code for this transition
     * parameter.
     */
    @Override
    public void visit(final SmcParameter parameter)
    {
        mTarget.print(parameter.getName());
        return;
    } // end of visit(SmcParameter)

    //
    // end of SmcVisitor Abstract Method Impelementation.
    //-----------------------------------------------------------
} // end of class SmcPythonGenerator

//
// CHANGE LOG
// $Log: SmcPythonGenerator.java,v $
// Revision 1.17  2014/07/12 08:18:18  fperrad
// compat python3
//
// Revision 1.16  2013/07/14 14:32:38  cwrapp
// check in for release 6.2.0
//
// Revision 1.15  2012/05/13 16:31:10  fperrad
// fix 3525846 : endless recursion with guarded transitions in Default state
//
// Revision 1.14  2012/04/18 07:43:38  fperrad
// fix #3519013
//
// Revision 1.13  2011/11/20 14:58:33  cwrapp
// Check in for SMC v. 6.1.0
//
// Revision 1.12  2010/05/19 09:08:17  fperrad
// fix #3003558
//
// Revision 1.11  2010/03/15 16:46:11  fperrad
// fix indent with -g1
//
// Revision 1.10  2010/03/05 21:29:53  fperrad
// Allows property with Groovy, Lua, Perl, Python, Ruby & Scala
//
// Revision 1.9  2009/12/17 19:51:43  cwrapp
// Testing complete.
//
// Revision 1.8  2009/11/27 17:19:21  fperrad
// Implemented feature req. #2718892 for Lua, Perl, PHP, Python, Ruby &Scala
//
// Revision 1.7  2009/11/25 22:30:19  cwrapp
// Fixed problem between %fsmclass and sm file names.
//
// Revision 1.6  2009/11/24 20:42:39  cwrapp
// v. 6.0.1 update
//
// Revision 1.5  2009/10/06 15:31:59  kgreg99
// 1. Started implementation of feature request #2718920.
//     1.1 Added method boolean isStatic() to SmcAction class. It returns false now, but is handled in following language generators: C#, C++, java, php, VB. Instance identificator is not added in case it is set to true.
// 2. Resolved confusion in "emtyStateStack" keyword handling. This keyword was not handled in the same way in all the generators. I added method boolean isEmptyStateStack() to SmcAction class. This method is used instead of different string comparisons here and there. Also the generated method name is fixed, not to depend on name supplied in the input sm file.
//
// Revision 1.4  2009/09/05 15:39:20  cwrapp
// Checking in fixes for 1944542, 1983929, 2731415, 2803547 and feature 2797126.
//
// Revision 1.3  2009/04/19 14:35:04  cwrapp
// Add initial state to FSMContext constructor. Added enterStartState method to application FSMContext subclass.
//
// Revision 1.2  2009/03/27 09:41:47  cwrapp
// Added F. Perrad changes back in.
//
// Revision 1.1  2009/03/01 18:20:42  cwrapp
// Preliminary v. 6.0.0 commit.
//
//
