//
// The contents of this file are subject to the Mozilla Public
// License Version 1.1 (the "License"); you may not use this file
// except in compliance with the License. You may obtain a copy
// of the License at http://www.mozilla.org/MPL/
//
// Software distributed under the License is distributed on an
// "AS IS" basis, WITHOUT WARRANTY OF ANY KIND, either express or
// implied. See the License for the specific language governing
// rights and limitations under the License.
//
// The Original Code is State Machine Compiler (SMC).
//
// The Initial Developer of the Original Code is Charles W. Rapp.
// Portions created by Charles W. Rapp are
// Copyright (C) 2005 - 2009, 2019. Charles W. Rapp.
// All Rights Reserved.
//
// Port to Scala by Francois Perrad, francois.perrad@gadz.org
// Copyright 2008-2009, Francois Perrad.
// All Rights Reserved.
//
// Contributor(s):
//   Eitan Suez contributed examples/Ant.
//   (Name withheld) contributed the C# code generation and
//   examples/C#.
//   Francois Perrad contributed the Python code generation and
//   examples/Python, Perl code generation and examples/Perl,
//   Ruby code generation and examples/Ruby, Lua code generation
//   and examples/Lua.
//   Chris Liscio contributed the Objective-C code generation
//   and examples/ObjC.
//
// RCS ID
// $Id: SmcScalaGenerator.java,v 1.14 2013/07/14 14:32:38 cwrapp Exp $
//
// CHANGE LOG
// (See the bottom of this file.)
//

package net.sf.smc.generator;

import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import net.sf.smc.model.SmcAction;
import net.sf.smc.model.SmcElement;
import net.sf.smc.model.SmcElement.TransType;
import net.sf.smc.model.SmcFSM;
import net.sf.smc.model.SmcGuard;
import net.sf.smc.model.SmcMap;
import net.sf.smc.model.SmcParameter;
import net.sf.smc.model.SmcState;
import net.sf.smc.model.SmcTransition;
import net.sf.smc.model.SmcVisitor;
import net.sf.smc.model.TargetLanguage;

/**
 * Visits the abstract syntax tree, emitting Scala code.
 * @see SmcElement
 * @see SmcCodeGenerator
 * @see SmcVisitor
 * @see SmcOptions
 *
 * @author Francois Perrad
 */

public final class SmcScalaGenerator
    extends SmcCodeGenerator
{
//---------------------------------------------------------------
// Member data
//

//---------------------------------------------------------------
// Member methods
//

    //-----------------------------------------------------------
    // Constructors.
    //

    /**
     * Creates a Scala code generator for the given options.
     * @param options The target code generator options.
     */
    public SmcScalaGenerator(final SmcOptions options)
    {
        super (options, TargetLanguage.SCALA.suffix());
    } // end of SmcScalaGenerator(SmcOptions)

    //
    // end of Constructors.
    //-----------------------------------------------------------

    //-----------------------------------------------------------
    // SmcVisitor Abstract Method Impelementation.
    //

    /**
     * Emits Scala code for the finite state machine.
     * @param fsm emit Scala code for this finite state machine.
     */
    @Override
    public void visit(final SmcFSM fsm)
    {
        String rawSource = fsm.getSource();
        String packageName = fsm.getPackage();
        String context = fsm.getContext();
        String fsmClassName = fsm.getFsmClassName();
        String startState = fsm.getStartState();
        List<SmcMap> maps = fsm.getMaps();
        List<SmcTransition> transitions;
        Iterator<SmcParameter> pit;
        String transName;
        String javaState;
        String separator;
        int index;
        List<SmcParameter> params;

        mTarget.println("// ex: set ro:");
        mTarget.println("// DO NOT EDIT.");
        mTarget.println(
            "// generated by smc (http://smc.sourceforge.net/)");
        mTarget.print("// from file : ");
        mTarget.print(mSrcfileBase);
        mTarget.println(".sm");

        // Dump out the raw target code, if any.
        if (rawSource != null && rawSource.length() > 0)
        {
            mTarget.println();
            mTarget.println(rawSource);
        }

        // If a package has been specified, generate the
        // package statement now.
        if (packageName != null && packageName.length() > 0)
        {
            mTarget.println();
            mTarget.print("package ");
            mTarget.println(packageName);
        }

        mTarget.println();
        if (mSyncFlag)
        {
            mTarget.println("import scala.concurrent");
            mTarget.println();
        }
        // Do user-specified imports now.
        for (String imp: fsm.getImports())
        {
            mTarget.print("import ");
            mTarget.println(imp);
        }

        mTarget.println();

        // The context clas contains all the state classes as
        // inner classes, so generate the context first rather
        // than last.
        mTarget.print("class ");
        mTarget.print(fsmClassName);
        mTarget.print("(owner: ");
        mTarget.print(context);
        mTarget.print(") extends statemap.FSMContext[");
        mTarget.print(context);
        mTarget.println("State] {");

        mTarget.println();
        mTarget.print("    private val _owner: ");
        mTarget.print(context);
        mTarget.println(" = owner");
        mTarget.println();

        // The state name "map::state" must be changed to
        // "map.state".
        if ((index = startState.indexOf("::")) >= 0)
        {
            javaState =
                startState.substring(0, index) +
                "." +
                startState.substring(index + 2);
        }
        else
        {
            javaState = startState;
        }

        mTarget.print("    setState(");
        mTarget.print(javaState);
        mTarget.println(")");

        mTarget.println();

        // Generate the default transition methods.
        // Get the transition list for the entire FSM.
        transitions = fsm.getTransitions();

        // Generate the transition methods.
        for (SmcTransition trans: transitions)
        {
            if (trans.getName().equals("Default") == false)
            {
                mTarget.print("    def ");
                mTarget.print(trans.getName());
                mTarget.print("(");

                params = trans.getParameters();
                for (pit = params.iterator(), separator = "";
                     pit.hasNext();
                     separator = ", ")
                {
                    mTarget.print(separator);
                    (pit.next()).accept(this);
                }
                mTarget.print("): Unit = ");
                // If the -sync flag was specified, then output
                // the "synchronized" keyword.
                if (mSyncFlag)
                {
                    mTarget.print("synchronized ");
                }
                mTarget.println("{");

                // Save away the transition name in case it is
                // need in an UndefinedTransitionException.
                mTarget.print("        _transition = \"");
                mTarget.print(trans.getName());
                mTarget.println("\"");

                mTarget.print("        getState().");
                mTarget.print(trans.getName());
                mTarget.print("(this");

                for (pit = params.iterator();
                     pit.hasNext();
                    )
                {
                    mTarget.print(", ");
                    mTarget.print((pit.next()).getName());
                }
                mTarget.println(")");
                mTarget.println("        _transition = \"\"");

                mTarget.println("    }");
                mTarget.println();
            }
        }

        // enterStartState()
        // Execute the start state's entry actions.
        mTarget.println("    override def enterStartState(): Unit = {");
        mTarget.println("        getState().Entry(this)");
        mTarget.println("    }");
        mTarget.println();

        // getOwner() method.
        mTarget.print("    def getOwner(): ");
        mTarget.print(context);
        mTarget.println(" = _owner");
        mTarget.println();

        if (mReflectFlag)
        {
            // getStates() method.
            mTarget.print("    def getStates(): List[");
            mTarget.print(context);
            mTarget.println("State] = List(");
            separator = "";
            for (SmcMap map: maps)
            {
                String mapName = map.getName();

                for (SmcState state: map.getStates())
                {
                    mTarget.print(separator);
                    mTarget.print("        ");
                    mTarget.print(mapName);
                    mTarget.print(".");
                    mTarget.print(state.getClassName());
                    separator = ",\n";
                }
            }
            mTarget.println();
            mTarget.println("    )");
            mTarget.println();

            // getTransitions() method.
            mTarget.println("    def getTransitions(): List[String] = List(");
            separator = "";
            for (SmcTransition trans: transitions)
            {
                mTarget.print(separator);
                mTarget.print("        \"");
                mTarget.print(trans.getName());
                mTarget.print("\"");
                separator = ",\n";
            }
            mTarget.println();
            mTarget.println("    )");
            mTarget.println();
        }

        // End of context class.
        mTarget.println("}");
        mTarget.println();

        // Declare the base state class.
        mTarget.print("class ");
        mTarget.print(context);
        mTarget.print("State(name: String, id: Int)");
        if (mSerialFlag)
        {
            mTarget.print(" extends Serializable");
        }
        mTarget.println(" {");
        mTarget.println("    private val _name = name");
        mTarget.println("    private val _id = id");
        mTarget.println();
        mTarget.println("    def getName(): String = _name");
        mTarget.println();
        mTarget.println("    override def toString(): String = _name");
        mTarget.println();

        mTarget.print("    def Entry(context: ");
        mTarget.print(fsmClassName);
        mTarget.println("): Unit = {}");
        mTarget.print("    def Exit(context: ");
        mTarget.print(fsmClassName);
        mTarget.println("): Unit = {}");
        mTarget.println();

        // Generate the default transition definitions.
        for (SmcTransition trans: transitions)
        {
            transName = trans.getName();

            // Don't generate the Default transition here.
            if (transName.equals("Default") == false)
            {
                mTarget.print("    def ");
                mTarget.print(transName);
                mTarget.print("(context: ");
                mTarget.print(fsmClassName);
                mTarget.print("");

                for (SmcParameter param: trans.getParameters())
                {
                    mTarget.print(", ");
                    param.accept(this);
                }

                mTarget.println("): Unit = {");

                // If this method is reached, that means that
                // this transition was passed to a state which
                // does not define the transition. Call the
                // state's default transition method.
                mTarget.println("        Default(context)");

                mTarget.println("    }");
                mTarget.println();
            }
        }

        // Generate the overall Default transition for all maps.
        mTarget.print("    def Default(context: ");
        mTarget.print(fsmClassName);
        mTarget.println("): Unit = {");

        if (mDebugLevel >= DEBUG_LEVEL_0)
        {
            mTarget.println(
                "        if (context.getDebugFlag())");
            mTarget.println(
                "            context.getDebugStream().println(\"TRANSITION   : Default\")");
            mTarget.println();
        }

        mTarget.println(
            "        throw new statemap.TransitionUndefinedException(");
        mTarget.println(
            "                \"State: \" + context.getState()._name +");
        mTarget.println(
            "                \", Transition: \" + context.getTransition())");
        mTarget.println("    }");

        // End of state class.
        mTarget.println();
        mTarget.println("}");
        mTarget.println();

        // Have each map print out its target code now.
        for (SmcMap map: maps)
        {
            map.accept(this);
        }

        return;
    } // end of visit(SmcFSM)

    /**
     * Emits Scala code for the FSM map.
     * @param map emit Scala code for this map.
     */
    @Override
    public void visit(final SmcMap map)
    {
        List<SmcTransition> definedDefaultTransitions;
        SmcState defaultState = map.getDefaultState();
        String context = map.getFSM().getContext();
        String mapName = map.getName();
        List<SmcState> states = map.getStates();

        // Initialize the default transition list to all the
        // default state's transitions.
        if (defaultState != null)
        {
            definedDefaultTransitions =
                defaultState.getTransitions();
        }
        else
        {
            definedDefaultTransitions = new ArrayList<>();
        }

        // Declare the map default state class.
        mTarget.print("private class ");
        mTarget.print(mapName);
        mTarget.print("_Default(name: String, id: Int) extends ");
        mTarget.print(context);
        mTarget.println("State(name, id) {");

        // Declare the user-defined default transitions first.
        mIndent = "    ";
        for (SmcTransition trans: definedDefaultTransitions)
        {
            trans.accept(this);
        }

        // If -reflect was specified, then generate the
        // _transitions map.
        if (mReflectFlag)
        {
            List<SmcTransition> allTransitions =
                map.getFSM().getTransitions();
            String transName;
            int transDefinition;

            // Now output the transition collection's
            // initialization.
            mTarget.println();
            mTarget.print("    def getTransitions(): Map[String, Int] = Map(");

            // Now place all transition names and states into the
            // map.
            String sep = "";
            for (SmcTransition transition: allTransitions)
            {
                transName = transition.getName();

                // If the transition is defined in this map's
                // default state, then the value is 2.
                if (definedDefaultTransitions.contains(transition))
                {
                    transDefinition = 2;
                }
                // Otherwise the value is 0 - undefined.
                else
                {
                    transDefinition = 0;
                }

                mTarget.println(sep);
                mTarget.print("        \"");
                mTarget.print(transName);
                mTarget.print("\" -> ");
                mTarget.print(transDefinition);
                sep = ",";
            }
            mTarget.println();
            mTarget.println("    )");
            mTarget.println();
        }

        // The map class has been defined.
        mTarget.println("}");

        // Have each state now generate its code. Each state
        // class is an inner class.
        for (SmcState state: states)
        {
            state.accept(this);
        }

        // Declare the map class.
        mTarget.println();
        mTarget.print("private object ");
        mTarget.print(mapName);
        mTarget.println(" {");

        // Declare each of the state class member data.
        for (SmcState state: states)
        {
            mTarget.print("    val ");
            mTarget.print(state.getInstanceName());
            mTarget.print(" = new ");
            mTarget.print(mapName);
            mTarget.print('_');
            mTarget.print(state.getClassName());
            mTarget.print("(\"");
            mTarget.print(mapName);
            mTarget.print('.');
            mTarget.print(state.getClassName());
            mTarget.print("\", ");
            mTarget.print(SmcMap.getNextStateId());
            mTarget.println(")");
        }

        // Create a default state as well.
        mTarget.print("    val Default = new ");
        mTarget.print(mapName);
        mTarget.print("_Default(\"");
        mTarget.print(mapName);
        mTarget.println(".Default\", -1)");

        // End of the map class.
        mTarget.println("}");
        mTarget.println();

        return;
    } // end of visit(SmcMap)

    /**
     * Emits Scala code for this FSM state.
     * @param state emits Scala code for this state.
     */
    @Override
    public void visit(final SmcState state)
    {
        SmcMap map = state.getMap();
        String context = map.getFSM().getContext();
        String fsmClassName = map.getFSM().getFsmClassName();
        String mapName = map.getName();
        String stateName = state.getClassName();
        List<SmcAction> actions;
        String indent2;

        mTarget.println();
        mTarget.print("private class ");
        mTarget.print(mapName);
        mTarget.print('_');
        mTarget.print(stateName);
        mTarget.print("(name: String, id: Int) extends ");
        mTarget.print(mapName);
        mTarget.println("_Default(name, id) {");

        // Add the Entry() and Exit() member functions if this
        // state defines them.
        actions = state.getEntryActions();
        if (actions != null && actions.size() > 0)
        {
            mTarget.println();
            mTarget.print("    override def Entry (context: ");
            mTarget.print(fsmClassName);
            mTarget.println("): Unit = {");

            // Declare the "ctxt" local variable.
            mTarget.println("        val ctxt = context.getOwner()");
            mTarget.println();

            // Generate the actions associated with this code.
            indent2 = mIndent;
            mIndent = "        ";
            for (SmcAction action: actions)
            {
                action.accept(this);
            }

            mIndent = indent2;

            // End the Entry() member function with a return.
            mTarget.println("    }");
        }

        actions = state.getExitActions();
        if (actions != null && actions.size() > 0)
        {
            mTarget.println();
            mTarget.print("    override def Exit (context: ");
            mTarget.print(fsmClassName);
            mTarget.println("): Unit = {");

            // Declare the "ctxt" local variable.
            mTarget.print("        val ctxt: ");
            mTarget.print(context);
            mTarget.println(" = context.getOwner()");
            mTarget.println();

            // Generate the actions associated with this code.
            mIndent = "        ";
            for (SmcAction action: actions)
            {
                action.accept(this);
            }

            // End the Exit() member function with a return.
            mTarget.println("    }");
        }

        // Have each transition generate its code.
        mIndent = "    ";
        for (SmcTransition transition: state.getTransitions())
        {
            transition.accept(this);
        }

        // If -reflect was specified, then generate the
        // _transitions map.
        if (mReflectFlag)
        {
            List<SmcTransition> allTransitions =
                map.getFSM().getTransitions();
            List<SmcTransition> stateTransitions =
                state.getTransitions();
            SmcState defaultState = map.getDefaultState();
            List<SmcTransition> defaultTransitions;
            String transName;
            int transDefinition;

            // Initialize the default transition list to all the
            // default state's transitions.
            if (defaultState != null)
            {
                defaultTransitions =
                    defaultState.getTransitions();
            }
            else
            {
                defaultTransitions = new ArrayList<>();
            }

            // Now output the transition collection's
            // initialization.
            mTarget.println();
            mTarget.print("    override def getTransitions(): Map[String, Int] = Map(");

            // Now place all transition names and states into the
            // map.
            String sep = "";
            for (SmcTransition transition: allTransitions)
            {
                transName = transition.getName();

                // If the transition is in this state, then its
                // value is 1.
                if (stateTransitions.contains(transition))
                {
                    transDefinition = 1;
                }
                // If the transition is defined in this map's
                // default state, then the value is 2.
                else if (defaultTransitions.contains(transition))
                {
                    transDefinition = 2;
                }
                // Otherwise the value is 0 - undefined.
                else
                {
                    transDefinition = 0;
                }

                mTarget.println(sep);
                mTarget.print("        \"");
                mTarget.print(transName);
                mTarget.print("\" -> ");
                mTarget.print(transDefinition);
                sep = ",";
            }
            mTarget.println();
            mTarget.println("    )");
            mTarget.println();
        }

        // End of this state class declaration.
        mTarget.println("}");

        return;
    } // end of visit(SmcState)

    /**
     * Emits Scala code for this FSM state transition.
     * @param transition emits Scala code for this state transition.
     */
    @Override
    public void visit(final SmcTransition transition)
    {
        SmcState state = transition.getState();
        SmcMap map = state.getMap();
        String fsmClassName = map.getFSM().getFsmClassName();
        String context = map.getFSM().getContext();
        String mapName = map.getName();
        String stateName = state.getClassName();
        String transName = transition.getName();
        List<SmcParameter> parameters =
            transition.getParameters();
        List<SmcGuard> guards = transition.getGuards();
        Iterator<SmcGuard> git = guards.iterator();
        SmcGuard guard;
        SmcGuard nullGuard = null;

        mTarget.println();
        mTarget.print(mIndent);
        mTarget.print("override def ");
        mTarget.print(transName);
        mTarget.print("(context: ");
        mTarget.print(fsmClassName);
        mTarget.print("");

        // Add user-defined parameters.
        for (SmcParameter parameter: parameters)
        {
            mTarget.print(", ");
            parameter.accept(this);
        }
        mTarget.println("): Unit = {");

        // All transitions have a "ctxt" local variable.
        // 8/14/2003:
        // Do this only if there are any transition actions or
        // guard conditions which reference it.
        if (transition.hasCtxtReference())
        {
            mTarget.print(mIndent);
            mTarget.print("    ");
            mTarget.print("val ctxt: ");
            mTarget.print(context);
            mTarget.println(" = context.getOwner()");
            mTarget.println();
        }

        // Output transition to debug stream.
        if (mDebugLevel >= DEBUG_LEVEL_0)
        {
            mTarget.print(mIndent);
            mTarget.println("    if (context.getDebugFlag())");
            mTarget.print(mIndent);
            mTarget.print("        context.getDebugStream().println(");
            mTarget.print("\"LEAVING STATE   : ");
            mTarget.print(mapName);
            mTarget.print('.');
            mTarget.print(stateName);
            mTarget.println("\")");
        }

        // Loop through the guards and print each one.
        mGuardIndex = 0;
        mGuardCount = guards.size();
        while (git.hasNext())
        {
            guard = git.next();

            // Count up the guards with no condition.
            if (guard.getCondition().isEmpty())
            {
                nullGuard = guard;
            }
            else
            {
                guard.accept(this);
                ++mGuardIndex;
            }
        }

        // Is there an explicitly defined unguarded transition?
        if (nullGuard != null)
        {
            // Does this guard have any actions or is this guard
            // *not* an internal loopback transition?
            if (nullGuard.hasActions() ||
                !(nullGuard.getEndState()).equals(SmcElement.NIL_STATE) ||
                nullGuard.getTransType() == TransType.TRANS_PUSH ||
                nullGuard.getTransType() == TransType.TRANS_POP)
            {
                // Need to output either the action and/or the
                // next state, so output the guard.
                nullGuard.accept(this);
            }

            mTarget.println();
        }
        // If all guards have a condition, then create a final
        // "else" clause which passes control to the default
        // transition. Pass all arguments into the default
        // transition.
        else if (mGuardIndex > 0)
        {
            if (mGuardCount == 1)
            {
                mTarget.print(mIndent);
                mTarget.println("    }");
            }

            mTarget.print(mIndent);
            mTarget.println("    else {");

            // Call the super class' transition method using
            // the "super" keyword and not the class name.
            mTarget.print(mIndent);
            mTarget.print("        super.");
            mTarget.print(transName);
            mTarget.print("(context");

            for (SmcParameter param: parameters)
            {
                mTarget.print(", ");
                mTarget.print(param.getName());
            }

            mTarget.println(")");
            mTarget.print(mIndent);
            mTarget.println("    }");
            mTarget.println();
        }
        // Need to add a final newline after a multiguard block.
        else if (mGuardCount > 1)
        {
            mTarget.println();
            mTarget.println();
        }

        mTarget.print(mIndent);
        mTarget.println("}");

        return;
    } // end of visit(SmcTransition)

    /**
     * Emits Scala code for this FSM transition guard.
     * @param guard emits Scala code for this transition guard.
     */
    @Override
    public void visit(final SmcGuard guard)
    {
        SmcTransition transition = guard.getTransition();
        SmcState state = transition.getState();
        SmcMap map = state.getMap();
        String mapName = map.getName();
        String stateName = state.getClassName();
        String transName = transition.getName();
        TransType transType = guard.getTransType();
        boolean loopbackFlag;
        String indent2;
        String indent3;
        String indent4;
        String endStateName = guard.getEndState();
        String fqEndStateName;
        String pushStateName = guard.getPushState();
        String condition = guard.getCondition();
        List<SmcAction> actions = guard.getActions();
        boolean hasActions = !(actions.isEmpty());

        // If this guard's end state is not of the form
        // "map::state", then prepend the map name to the
        // state name.
        // DON'T DO THIS IF THIS IS A POP TRANSITION!
        // The "state" is actually a transition name.
        if (transType != TransType.TRANS_POP &&
            endStateName.length () > 0 &&
            endStateName.equals(SmcElement.NIL_STATE) == false)
        {
            endStateName = scopeStateName(endStateName, mapName);
        }

        // Qualify the state and push state names as well.
        stateName = scopeStateName(stateName, mapName);
        pushStateName = scopeStateName(pushStateName, mapName);

        loopbackFlag = isLoopback(transType, endStateName);

        // The guard code generation is a bit tricky. The first
        // question is how many guards are there? If there are
        // more than one, then we will need to generate the
        // proper "if-then-else" code.
        if (mGuardCount > 1)
        {
            indent2 = mIndent + "        ";

            // There are multiple guards.
            // Is this the first guard?
            if (mGuardIndex == 0 && condition.length() > 0)
            {
                // Yes, this is the first. This means an "if"
                // should be used.
                mTarget.print(mIndent);
                mTarget.print("    if (");
                mTarget.print(condition);
                mTarget.println(") {");
            }
            else if (condition.length() > 0)
            {
                // No, this is not the first transition but it
                // does have a condition. Use an "else if".
                mTarget.println();
                mTarget.print(mIndent);
                mTarget.print("    else if (");
                mTarget.print(condition);
                mTarget.println(") {");
            }
            else
            {
                // This is not the first transition and it has
                // no condition.
                mTarget.println();
                mTarget.print(mIndent);
                mTarget.println("    else {");
            }
        }
        // There is only one guard. Does this guard have a
        // condition?
        else if (condition.length() == 0)
        {
            // No. This is a plain, old. vanilla transition.
            indent2 = mIndent + "    ";
        }
        else
        {
            // Yes there is a condition.
            indent2 = mIndent + "        ";

            mTarget.print(mIndent);
            mTarget.print("    if (");
            mTarget.print(condition);
            mTarget.println(") {");
        }

        // Now that the necessary conditions are in place, it's
        // time to dump out the transition's actions. First, do
        // the proper handling of the state change. If this
        // transition has no actions, then set the end state
        // immediately. Otherwise, unset the current state so
        // that if an action tries to issue a transition, it will
        // fail.
        if (hasActions == false)
        {
            fqEndStateName = endStateName;
        }
        // Save away the current state if this is a loopback
        // transition. Storing current state allows the
        // current state to be cleared before any actions are
        // executed. Remember: actions are not allowed to
        // issue transitions and clearing the current state
        // prevents them from doing do.
        else if (loopbackFlag)
        {
            fqEndStateName = "endState";

            mTarget.print(indent2);
            mTarget.print("val ");
            mTarget.print(fqEndStateName);
            mTarget.println(" = context.getState()");
        }
        else
        {
            fqEndStateName = endStateName;
        }

        mTarget.println();

        // Dump out the exit actions - but only for the first
        // guard.
        // v. 1.0, beta 3: Not any more. The exit actions are
        // executed only if 1) this is a standard, non-loopback
        // transition or a pop transition.
        if (transType == TransType.TRANS_POP ||
            loopbackFlag == false)
        {
            if (mDebugLevel >= DEBUG_LEVEL_1)
            {
                mTarget.print(indent2);
                mTarget.println("if (context.getDebugFlag())");
                mTarget.print(indent2);
                mTarget.print(
                    "    context.getDebugStream().println(");
                mTarget.print("\"BEFORE EXIT     : ");
                mTarget.print(stateName);
                mTarget.println(".Exit(fsm)\")");
            }

            mTarget.print(indent2);
            mTarget.println("context.getState().Exit(context)");

            if (mDebugLevel >= DEBUG_LEVEL_1)
            {
                mTarget.print(indent2);
                mTarget.println("if (context.getDebugFlag())");
                mTarget.print(indent2);
                mTarget.print(
                    "    context.getDebugStream().println(");
                mTarget.print("\"AFTER EXIT      : ");
                mTarget.print(stateName);
                mTarget.println(".Exit(fsm)\")");
            }
        }

        if (mDebugLevel >= DEBUG_LEVEL_0)
        {
            List<SmcParameter> parameters =
                transition.getParameters();
            Iterator<SmcParameter> pit;
            String sep;

            mTarget.print(indent2);
            mTarget.println("if (context.getDebugFlag())");
            mTarget.print(indent2);
            mTarget.print(
                "    context.getDebugStream().println(");
            mTarget.print("\"ENTER TRANSITION: ");
            mTarget.print(stateName);
            mTarget.print('.');
            mTarget.print(transName);

            mTarget.print('(');
            for (pit = parameters.iterator(), sep = "";
                 pit.hasNext();
                 sep = ", ")
            {
                mTarget.print(sep);
                (pit.next()).accept(this);
            }
            mTarget.println(")\")");
        }

        // Dump out this transition's actions.
        if (hasActions == false)
        {
            if (condition.length() > 0)
            {
                mTarget.print(indent2);
                mTarget.println("// No actions.");
            }

            indent3 = indent2;
        }
        else
        {
            // Now that we are in the transition, clear the
            // current state.
            mTarget.print(indent2);
            mTarget.println("context.clearState()");

            // v. 2.0.0: Place the actions inside a try/finally
            // block. This way the state will be set before an
            // exception leaves the transition method.
            // v. 2.2.0: Check if the user has turned off this
            // feature first.
            if (mNoCatchFlag == false)
            {
                mTarget.print(indent2);
                mTarget.println("try {");

                indent3 = indent2 + "    ";
            }
            else
            {
                indent3 = indent2;
            }

            indent4 = mIndent;
            mIndent = indent3;

            for (SmcAction action: actions)
            {
                action.accept(this);
            }

            mIndent = indent4;

            // v. 2.2.0: Check if the user has turned off this
            // feature first.
            if (mNoCatchFlag == false)
            {
                mTarget.print(indent2);
                mTarget.println('}');
                mTarget.print(indent2);
                mTarget.println("finally {");
            }
        }

        if (mDebugLevel >= DEBUG_LEVEL_0)
        {
            List<SmcParameter> parameters =
                transition.getParameters();
            Iterator<SmcParameter> pit;
            String sep;

            mTarget.print(indent3);
            mTarget.println("if (context.getDebugFlag())");
            mTarget.print(indent3);
            mTarget.print(
                "    context.getDebugStream().println(");
            mTarget.print("\"EXIT TRANSITION : ");
            mTarget.print(stateName);
            mTarget.print('.');
            mTarget.print(transName);

            mTarget.print('(');
            for (pit = parameters.iterator(), sep = "";
                 pit.hasNext();
                 sep = ", ")
            {
                mTarget.print(sep);
                (pit.next()).accept(this);
            }
            mTarget.println(")\")");
        }

        // Print the setState() call, if necessary. Do NOT
        // generate the set state it:
        // 1. The transition has no actions AND is a loopback OR
        // 2. This is a push or pop transition.
        if (transType == TransType.TRANS_SET &&
            (hasActions || loopbackFlag == false))
        {
            mTarget.print(indent3);
            mTarget.print("context.setState(");
            mTarget.print(fqEndStateName);
            mTarget.println(")");
        }
        else if (transType == TransType.TRANS_PUSH)
        {
            // Set the next state so this it can be pushed
            // onto the state stack. But only do so if a clear
            // state was done.
            if (loopbackFlag == false || hasActions)
            {
                mTarget.print(indent3);
                mTarget.print("context.setState(");
                mTarget.print(fqEndStateName);
                mTarget.println(")");
            }

            // Before doing the push, execute the end state's
            // entry actions (if any) if this is not a loopback.
            if (loopbackFlag == false)
            {
                if (mDebugLevel >= DEBUG_LEVEL_1)
                {
                    mTarget.print(indent3);
                    mTarget.println(
                        "if (context.getDebugFlag())");
                    mTarget.print(indent3);
                    mTarget.print(
                        "    context.getDebugStream().println(");
                    mTarget.print("\"BEFORE ENTRY    : ");
                    mTarget.print(fqEndStateName);
                    mTarget.println(".Entry(fsm)\")");
                }

                mTarget.print(indent3);
                mTarget.println("context.getState().Entry(context)");

                if (mDebugLevel >= DEBUG_LEVEL_1)
                {
                    mTarget.print(indent3);
                    mTarget.println(
                        "if (context.getDebugFlag())");
                    mTarget.print(indent3);
                    mTarget.print(
                        "    context.getDebugStream().println(");
                    mTarget.print("\"AFTER ENTRY     : ");
                    mTarget.print(fqEndStateName);
                    mTarget.println(".Entry(fsm)\")");
                }
            }

            mTarget.print(indent3);
            mTarget.print("context.pushState(");
            mTarget.print(pushStateName);
            mTarget.println(")");
        }
        else if (transType == TransType.TRANS_POP)
        {
            mTarget.print(indent3);
            mTarget.println("context.popState()");
        }

        // Perform the new state's enty actions.
        // v. 1.0, beta 3: Not any more. The entry actions are
        // executed only if 1) this is a standard, non-loopback
        // transition or a push transition.
        if ((transType == TransType.TRANS_SET &&
             loopbackFlag == false) ||
             transType == TransType.TRANS_PUSH)
        {
            if (mDebugLevel >= DEBUG_LEVEL_1)
            {
                mTarget.print(indent3);
                mTarget.println("if (context.getDebugFlag())");
                mTarget.print(indent3);
                mTarget.print(
                    "    context.getDebugStream().println(");
                mTarget.print("\"BEFORE ENTRY    : ");
                mTarget.print(fqEndStateName);
                mTarget.println(".Entry(fsm)\")");
            }

            mTarget.print(indent3);
            mTarget.println("context.getState().Entry(context)");

            if (mDebugLevel >= DEBUG_LEVEL_1)
            {
                mTarget.print(indent3);
                mTarget.println("if (context.getDebugFlag())");
                mTarget.print(indent3);
                mTarget.print(
                    "    context.getDebugStream().println(");
                mTarget.print("\"AFTER ENTRY     : ");
                mTarget.print(fqEndStateName);
                mTarget.println(".Entry(fsm)\")");
            }
        }

        // If there was a try/finally, then put the closing
        // brace on the finally block.
        // v. 2.2.0: Check if the user has turned off this
        // feature first.
        if (hasActions && mNoCatchFlag == false)
        {
            mTarget.print(indent2);
            mTarget.println('}');
        }

        // If there is a transition associated with the pop, then
        // issue that transition here.
        if (transType == TransType.TRANS_POP &&
            endStateName.equals(SmcElement.NIL_STATE) == false &&
            endStateName.length() > 0)
        {
            String popArgs = guard.getPopArgs();

            mTarget.println();
            mTarget.print(indent2);
            mTarget.print("context.");
            mTarget.print(endStateName);
            mTarget.print("(");

            // Output any and all pop arguments.
            if (popArgs.length() > 0)
            {
                mTarget.print(popArgs);
            }
            mTarget.println(")");
        }

        // If this is a guarded transition, it will be necessary
        // to close off the "if" body. DON'T PRINT A NEW LINE!
        // Why? Because an "else" or "else if" may follow and we
        // won't know until we go back to the transition target
        // generator whether all clauses have been done.
        if (mGuardCount > 1)
        {
            mTarget.print(mIndent);
            mTarget.print("    }");
        }

        return;
    } // end of visit(SmcGuard)

    /**
     * Emits Scala code for this FSM action.
     * @param action emits Scala code for this action.
     */
    @Override
    public void visit(final SmcAction action)
    {
        String name = action.getName();
        List<String> arguments = action.getArguments();

        if (action.isProperty())
        {
            mTarget.print(mIndent);
            mTarget.print("ctxt.");
            mTarget.print(name);
            mTarget.print(" = ");
            mTarget.println(arguments.get(0));
        }
        else
        {
            // Need to distinguish between FSMContext actions and
            // application class actions. If the action is
            // "emptyStateStack", then pass it to the context.
            // Otherwise, let the application class handle it.
            mTarget.print(mIndent);
            if (action.isEmptyStateStack())
            {
                mTarget.println("context.emptyStateStack()");
            }
            else
            {
                Iterator<String> it;
                String sep;

                mTarget.print("ctxt.");
	        mTarget.print(name);
	        mTarget.print("(");

	        for (it = arguments.iterator(), sep = "";
	             it.hasNext();
	             sep = ", ")
	        {
	            mTarget.print(sep);
	            mTarget.print(it.next());
	        }

	        mTarget.println(")");
            }
        }

        return;
    } // end of visit(SmcAction)

    /**
     * Emits Scala code for this transition parameter.
     * @param parameter emits Scala code for this transition
     * parameter.
     */
    @Override
    public void visit(final SmcParameter parameter)
    {
        mTarget.print(parameter.getName());
        mTarget.print(": ");
        mTarget.print(parameter.getType());

        return;
    } // end of visit(SmcParameter)

    //
    // end of SmcVisitor Abstract Method Impelementation.
    //-----------------------------------------------------------
} // end of class SmcScalaGenerator

//
// CHANGE LOG
// $Log: SmcScalaGenerator.java,v $
// Revision 1.14  2013/07/14 14:32:38  cwrapp
// check in for release 6.2.0
//
// Revision 1.13  2012/05/13 21:31:14  fperrad
// fix deprecation with Scala 2.9.1
//
// Revision 1.12  2011/11/20 14:58:33  cwrapp
// Check in for SMC v. 6.1.0
//
// Revision 1.11  2010/03/05 21:29:53  fperrad
// Allows property with Groovy, Lua, Perl, Python, Ruby & Scala
//
// Revision 1.10  2009/12/17 19:51:43  cwrapp
// Testing complete.
//
// Revision 1.9  2009/11/27 17:19:21  fperrad
// Implemented feature req. #2718892 for Lua, Perl, PHP, Python, Ruby &Scala
//
// Revision 1.8  2009/11/25 22:30:19  cwrapp
// Fixed problem between %fsmclass and sm file names.
//
// Revision 1.7  2009/11/24 20:42:39  cwrapp
// v. 6.0.1 update
//
// Revision 1.6  2009/10/06 15:31:59  kgreg99
// 1. Started implementation of feature request #2718920.
//     1.1 Added method boolean isStatic() to SmcAction class. It returns false now, but is handled in following language generators: C#, C++, java, php, VB. Instance identificator is not added in case it is set to true.
// 2. Resolved confusion in "emtyStateStack" keyword handling. This keyword was not handled in the same way in all the generators. I added method boolean isEmptyStateStack() to SmcAction class. This method is used instead of different string comparisons here and there. Also the generated method name is fixed, not to depend on name supplied in the input sm file.
//
// Revision 1.5  2009/09/12 21:44:49  kgreg99
// Implemented feature req. #2718941 - user defined generated class name.
// A new statement was added to the syntax: %fsmclass class_name
// It is optional. If not used, generated class is called as before "XxxContext" where Xxx is context class name as entered via %class statement.
// If used, generated class is called asrequested.
// Following language generators are touched:
// c, c++, java, c#, objc, lua, groovy, scala, tcl, VB
// This feature is not tested yet !
// Maybe it will be necessary to modify also the output file name.
//
// Revision 1.4  2009/09/05 15:39:20  cwrapp
// Checking in fixes for 1944542, 1983929, 2731415, 2803547 and feature 2797126.
//
// Revision 1.3  2009/04/23 13:12:08  fperrad
// Added enterStartState method
//
// Revision 1.2  2009/03/27 09:41:47  cwrapp
// Added F. Perrad changes back in.
//
// Revision 1.1  2009/03/01 18:20:42  cwrapp
// Preliminary v. 6.0.0 commit.
//
//
